version: "3"

tasks:
  switch:
    vars:
      HOSTNAME:
        sh: hostname
    deps:
      - "switch:{{.HOSTNAME}}"

  switch:*:
    vars:
      PROFILE: "{{index .MATCH 0}}"
    cmd: >-
      nix run home-manager/release-25.11 --
      switch
      --flake ~/Projects/etc#{{.PROFILE}}
      --impure
