#! /bin/zsh
# Custom X initialization script
# P.C. Shyamshankar <sykora@lucentbeing.com>

# Load some defaults
xrdb < ~/etc/x/xdefaults

# Load the Colemak keymap.
xmodmap ~/etc/x/colemak.xmodmap

# Make sure the CapsLock key (now backspace) can repeat.
xset r 66

# Set the mouse pointer.
xsetroot -cursor_name left_ptr

# Set the wallpaper
~/bin/cycle-wallpaper

# Start the scrobbler
sudo /etc/rc.d/mpdscribble restart

# Save my wrists.
xwrits +clock +breakclock +idle +top typetime=55 break=5 after=10 -multiply break=7 &

# /me loves lots of fast terminals
urxvtd -q -o -f

# Hide the mouse
unclutter -idle 5 -noevents -root &

# Reload my backgrounds
nitrogen --restore

# Start my favorite window manager.
xmonad
