#! /bin/zsh
# Custom X initialization script
# P.C. Shyamshankar <sykora@lucentbeing.com>

# Load some defaults
xrdb < ~/etc/x/xdefaults

source ~/etc/x/input/keyboard
source ~/etc/x/input/mouse
source ~/etc/x/input/synaptics

feh --bg-scale ~/img/wallpapers/current

# Disable the bell.
xset b off

# /me loves lots of fast terminals
urxvtd -q -o -f

# Hide the mouse
unclutter -grab -idle 5 -noevents -root &

# Start the screensaver.
xautolock -detectsleep &

# Start the xbindkeys listener
xbindkeys

# Start my favorite window manager.
xmonad
