- hosts: all
  vars:
    source: "{{ playbook_dir | dirname }}"
    target: "{{ ansible_env.HOME }}"
  tasks:
    - name: Deploy nix configuration
      tags: nix
      lineinfile:
        path: "{{ target }}/.config/nix/nix.conf"
        line: "experimental-features = nix-command flakes"
        create: true
    - name: Ensure target exists
      file:
        state: directory
        path: "{{ target }}"
    - name: Deploy Z-Shell Configuration
      tags: zsh
      block:
        - name: Deploy .zprofile
          copy:
            src: "{{ source }}/zsh/zprofile"
            dest: "{{ target }}/.zprofile"
        - name: Deploy .zshrc
          copy:
            src: "{{ source }}/zsh/zshrc"
            dest: "{{ target }}/.zshrc"
    - name: Deploy TERMINFO definitions
      tags: terminfo
      command: "tic -x -o {{ target }}/.terminfo {{ source }}/terminfo/xterm-24bit.terminfo"
    - name: Deploy Emacs Configuration
      tags: emacs
      block:
        - name: Create Emacs Directory
          file:
            path: "{{ target }}/.emacs.d"
            state: directory
        - name: Deploy Emacs Initialization File
          copy:
            src: "{{ source }}/emacs/init.el"
            dest: "{{ target }}/.emacs.d/init.el"
        - name: Deploy Emacs Color Theme
          copy:
            src: "{{ source }}/emacs/skywave-theme.el"
            dest: "{{ target }}/.emacs.d/skywave-theme.el"
    - name: Deploy TMux Configuration
      tags: tmux
      copy:
        src: "{{ source }}/tmux/tmux.conf"
        dest: "{{ target }}/.tmux.conf"
