- hosts: all
  vars:
    source: "{{ playbook_dir | dirname }}"
    target: "{{ ansible_env.HOME }}"
  tasks:
    - name: Ensure target exists
      file:
        state: directory
        path: "{{ target }}"
    - name: Deploy Z-Shell Configuration
      tags: zsh
      block:
        - name: Deploy .zprofile
          copy:
            src: "{{ source }}/zsh/zprofile"
            dest: "{{ target }}/.zprofile"
        - name: Deploy .zshrc
          copy:
            src: "{{ source }}/zsh/zshrc"
            dest: "{{ target }}/.zshrc"
    - name: Deploy Emacs Configuration
      tags: emacs
      block:
        - name: Create Emacs Directory
          file:
            path: "{{ target }}/.emacs.d"
            state: directory
        - copy:
            src: "{{ source }}/emacs/init.el"
            dest: "{{ target }}/.emacs.d/init.el"
        - copy:
            src: "{{ source }}/emacs/skywave-theme.el"
            dest: "{{ target }}/.emacs.d/skywave-theme.el"
    - name: Deploy TMux Configuration
      tags: tmux
      copy:
        src: "{{ source }}/tmux/tmux.conf"
        dest: "{{ target }}/.tmux.conf"
