- hosts: all
  vars:
    source: "{{ playbook_dir | dirname }}"
    target: "{{ ansible_env.HOME }}"
  tasks:
    - name: Deploy nix configuration
      tags: nix
      lineinfile:
        path: "{{ target }}/.config/nix/nix.conf"
        line: "experimental-features = nix-command flakes"
        create: true

    - name: Ensure target exists
      file:
        state: directory
        path: "{{ target }}"

    - name: Deploy Z-Shell Configuration
      tags: zsh
      block:
        - name: Deploy .zprofile
          copy:
            src: "{{ source }}/zsh/zprofile"
            dest: "{{ target }}/.zprofile"
        - name: Deploy .zshrc
          copy:
            src: "{{ source }}/zsh/zshrc"
            dest: "{{ target }}/.zshrc"

    - name: Deploy TERMINFO definitions
      tags: terminfo
      block:
        - name: Create temporary TERMINFO directory
          tempfile:
            state: directory
            suffix: terminfo
          register: terminfo_dir
          changed_when: False

        - name: Generate TERMINFO
          command: "tic -x -o {{ terminfo_dir.path }} {{ source }}/terminfo/xterm-24bit.terminfo"
          changed_when: False

        - name: Deploy TERMINFO
          copy:
            src: "{{ terminfo_dir.path }}/x"
            dest: "{{ target }}/.terminfo/"

        - name: Remove temporary TERMINFO directory
          file:
            path: "{{ terminfo_dir.path }}"
            state: absent
          changed_when: False

    - name: Deploy Emacs Configuration
      tags: emacs
      block:
        - name: Create Emacs Directory
          file:
            path: "{{ target }}/.emacs.d"
            state: directory

        - name: Deploy Emacs Initialization File
          copy:
            src: "{{ source }}/emacs/init.el"
            dest: "{{ target }}/.emacs.d/init.el"

        - name: Deploy Emacs Color Theme
          copy:
            src: "{{ source }}/emacs/skywave-theme.el"
            dest: "{{ target }}/.emacs.d/skywave-theme.el"

    - name: Deploy TMux Configuration
      tags: tmux
      copy:
        src: "{{ source }}/tmux/tmux.conf"
        dest: "{{ target }}/.tmux.conf"

    - name: Deploy Git Configuration
      tags: git
      copy:
        src: "{{ source }}/git/gitconfig"
        dest: "{{ target }}/.gitconfig"
