# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
# zprofile: Environment configuration for the Z-Shell
# P.C. Shyamshankar 'sykloid' <shyam@sykloid.org>

# This file is loaded in all login shells. If the shell is also interactive,
# this file is loaded *before* zshrc.

# The primary purpose of this file is to set environment variables for the
# benefit of any application launched as a child of this shell.

export FPATH=${HOME}/.zfunc:${FPATH}

export EDITOR=emacs

export LESS_TERMCAP_so=$(echo -e '\e[1;7m')
export LESS_TERMCAP_se=$(echo -e '\e[0m')
export MANROFFOPT="-c"
export MANPAGER="sh -c 'col -bx | bat -plman'"
export MANWIDTH=80

export PATH=${HOME}/.cargo/bin:${HOME}/.rye/bin:${HOME}/.ghcup/bin:${HOME}/.local/bin:${PATH}
export LD_LIBRARY_PATH=${HOME}/.local/lib:${LD_LIBRARY_PATH}
