# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
# zprofile: Environment configuration for the Z-Shell
# P.C. Shyamshankar 'sykloid' <shyam@sykloid.org>

# This file is loaded in all login shells. If the shell is also interactive,
# this file is loaded *before* zshrc.

# The primary purpose of this file is to set environment variables for the
# benefit of any application launched as a child of this shell.

# Putting such definitions in zshrc would prevent subshells from overriding them
# (they would be overridden again immediately); it is also not possible to put
# interactive configuration in this file under a [[ -o interactive ]] guard,
# since such configurations *are not* inherited by subshells.

# Hence, we are forced to use two files -- this one, and zshrc.

# Actually, three files: it is assumed that if the airlift software package has
# been deployed to this system, its path is stored in the $AIRLIFT environment
# variable. That must be done on a per deployment basis -- either in a
# Dockerfile, a nix shell hook, or in the case of a bare-metal environment, one
# of the only files which is read before this one -- zshenv.
if [[ -v AIRLIFT ]]; then
  export PATH=$AIRLIFT/bin:$PATH
  export LD_LIBRARY_PATH=$AIRLIFT/lib:$LD_LIBRARY_PATH
  export MANPATH=$AIRLIFT/share/man:$MANPATH

  export EDITOR=emacs

  export MANPAGER='bat --style=plain --language=man'
  export MANWIDTH=80
else
  print "\$AIRLIFT is not set; some tools may not be present."
  export EDITOR=vi
fi

export PATH=$HOME/.local/bin:$PATH
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
