;;; init -- Custom Emacs Configuration.
;;; P.C. Shyamshankar "sykora" <sykora@lucentbeing.com>

;;; Commentary:

;;; This configuration method is inspired by MilkyPostman's single-file setup at
;;; `http://milkbox.net/note/single-file-master-emacs-configuration/'. It makes
;;; use of a similar `after' macro --- now called `with-load', using 24.4's
;;; `with-eval-after-load'.

;;; Code:

;;;; Scaffolding
(defalias 'with-load 'with-eval-after-load)
(put 'with-load 'lisp-indent-function 1)

(defmacro with-load! (feature &rest body)
  "`require' + `with-load'.
Basically, first load `FEATURE', then evaluate `BODY'."
  (declare (indent defun))
  `(progn (require ,feature)
          (with-load ,feature
            ,@body)))

(defmacro with-hook (hook &rest body)
  "Add to the value of `HOOK', all of the actions in `BODY'."
  (declare (indent 1))
  `(add-hook ,hook (lambda () (progn ,@body))))

(defalias 'setc 'customize-set-variable)

;;;; Global Constants
(defconst instance-name
  (if (daemonp)
      (daemonp)
    (format "emacs-%d" (emacs-pid)))
  "Unique name of the current emacs instance.
Defaults to `server-name' if present, generated by PID otherwise.")

;;;; Packages and Libraries
(with-load 'emacs
  (require 'package)

  (set 'package-user-dir (concat user-emacs-directory "elpa/"))
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
  (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
  (package-initialize)

  (defvar user-lisp-directory (concat user-emacs-directory "lisp/"))
  (add-to-list 'load-path user-lisp-directory)

  (defvar user-theme-directory (concat user-lisp-directory "themes/"))
  (add-to-list 'custom-theme-load-path user-theme-directory)

  (set 'custom-file (concat user-lisp-directory "customizations.el"))

  (require 'alist-utils)
  (require 'autoload-provide-feature)

  (when (file-exists-p custom-file)
      (load custom-file)))

;;;; Miscellaneous Directives
(with-load 'emacs
  (put 'narrow-to-region 'disabled nil))

;;;; Mode Detection
(with-load 'emacs
  (autoload 'K3-mode "K3-mode")
  (add-to-list 'auto-mode-alist '("\\.k3" . K3-mode))
  (add-to-list 'auto-mode-alist '("\\.ldg" . ledger-mode))
  (add-to-list 'auto-mode-alist '("\\.md" . markdown-mode))
  (add-to-list 'auto-mode-alist '("\\.ya?ml" . yaml-mode))
  (add-to-list 'auto-mode-alist '("\\.zsh" . sh-mode)))

;;;; Appearance
(with-load 'emacs
  (set 'inhibit-splash-screen t)

  (blink-cursor-mode -1)
  (column-number-mode)
  (fringe-mode '(8 . 0))
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)

  (set 'scroll-step 1)

  (set-frame-font "Fantasque Sans Mono-11")

  (set 'default-frame-alist '((font . "Fantasque Sans Mono-11")))

  (if (daemonp)
      (add-hook 'after-make-frame-functions
                (lambda (frame)
                  (with-selected-frame frame
                    (load-theme 'skywave-gui))))
    (load-theme 'skywave-gui))

  (defalias 'yes-or-no-p 'y-or-n-p))

;;;; Interface
(with-load 'emacs
  (global-visual-line-mode)

  (set-default 'fill-column 100)
  (set-default 'indent-tabs-mode nil)
  (set-default 'tab-width 2)

  (set 'frame-title-format '("emacs" (:eval (format "@%s" instance-name)) ": %b"))

  (set 'blink-matching-delay 0.75)

  (with-hook 'prog-mode-hook
    (modify-syntax-entry ?{ "(}")
    (modify-syntax-entry ?} "){")

    (set 'show-trailing-whitespace t))

  (set 'sentence-end-double-space nil))

;;;; Files
(with-load 'emacs
  ; Backups
  (set 'backup-by-copying t)
  (set 'backup-directory-alist `(("." . ,(concat user-emacs-directory "tmp/backups/"))))
  (set 'delete-old-versions t)
  (set 'kept-new-versions 6)
  (set 'kept-old-versions 2)
  (set 'version-control t)

  ; Auto-Saves
  (set 'auto-save-file-name-transforms `((".*" ,(concat user-emacs-directory "tmp/auto-saves/") t))))

;;;; Evil/Keymaps
(with-load 'evil-autoloads
  (evil-mode t))

(with-load 'evil
  (define-key evil-normal-state-map "q" nil)
  (define-key evil-normal-state-map "Q" 'evil-record-macro)


  ;; Cursor Movement
  (define-key evil-normal-state-map "n" 'evil-backward-char)
  (define-key evil-normal-state-map "e" 'evil-next-visual-line)
  (define-key evil-normal-state-map "i" 'evil-previous-visual-line)
  (define-key evil-normal-state-map "o" 'evil-forward-char)

  (define-key evil-motion-state-map "n" 'evil-backward-char)
  (define-key evil-motion-state-map "e" 'evil-next-visual-line)
  (define-key evil-motion-state-map "i" 'evil-previous-visual-line)
  (define-key evil-motion-state-map "o" 'evil-forward-char)

  (define-key evil-visual-state-map "n" 'evil-backward-char)
  (define-key evil-visual-state-map "e" 'evil-next-visual-line)
  (define-key evil-visual-state-map "i" 'evil-previous-visual-line)
  (define-key evil-visual-state-map "o" 'evil-forward-char)

  ;; Window Movement
  (define-key evil-window-map "n" 'evil-window-left)
  (define-key evil-window-map "e" 'evil-window-down)
  (define-key evil-window-map "i" 'evil-window-up)
  (define-key evil-window-map "o" 'evil-window-right)

  (define-key evil-window-map "\C-n" 'evil-window-left)
  (define-key evil-window-map "\C-e" 'evil-window-down)
  (define-key evil-window-map "\C-i" 'evil-window-up)
  (define-key evil-window-map "\C-o" 'evil-window-right)

  (define-key evil-window-map "q" 'evil-window-delete)
  (define-key evil-window-map "d" 'delete-other-windows)
  (define-key evil-window-map "D" 'delete-other-windows-vertically)

  (define-key evil-window-map "u" 'winner-undo)
  (define-key evil-window-map "U" 'winner-redo)

  ;; Entering Insert Mode
  (define-key evil-normal-state-map "h" 'evil-insert-state)
  (define-key evil-normal-state-map "H" 'evil-insert-line)
  (define-key evil-normal-state-map "a" 'evil-append)
  (define-key evil-normal-state-map "A" 'evil-append-line)
  (define-key evil-normal-state-map "y" 'evil-open-below)
  (define-key evil-normal-state-map "Y" 'evil-open-above)

  ;; Copying and Pasting
  (define-key evil-normal-state-map "k" 'evil-yank)
  (define-key evil-normal-state-map "m" 'evil-paste-after)
  (define-key evil-normal-state-map "M" 'evil-paste-before)

  (define-key evil-visual-state-map "k" 'evil-yank)
  (define-key evil-visual-state-map "m" 'evil-paste-after)
  (define-key evil-visual-state-map "M" 'evil-paste-before)

  ;; Text-Objects and Motions
  (define-key evil-visual-state-map "y" 'evil-visual-exchange-corners)
  (define-key evil-visual-state-map "h" evil-inner-text-objects-map)
  (define-key evil-operator-state-map "h" evil-inner-text-objects-map)

  ;; Search
  (define-key evil-normal-state-map "t" 'evil-search-next)
  (define-key evil-normal-state-map "T" 'evil-search-previous)
  (define-key evil-motion-state-map "t" 'evil-search-next)
  (define-key evil-motion-state-map "T" 'evil-search-previous)

  ;; Miscellaneous -- the `s'-map is my `g'-map.
  (define-key evil-normal-state-map "s" nil)
  (define-key evil-normal-state-map "sv" 'evil-visual-restore)
  (define-key evil-normal-state-map "sff" 'ffap)
  (define-key evil-normal-state-map "sfo" 'ffap-other-window)

  ;; Inject window movement keys into emacs state.
  (define-key evil-emacs-state-map "\C-w" evil-window-map)

  (set 'evil-want-fine-undo nil))

;; Evil-Args
(with-load 'evil-args

  (add-to-list 'evil-args-openers "<")
  (add-to-list 'evil-args-closers ">")

  (add-to-list 'evil-args-delimiters ";")

  (with-load 'evil
    (define-key evil-inner-text-objects-map "," 'evil-inner-arg)
    (define-key evil-outer-text-objects-map "," 'evil-outer-arg)

    (define-key evil-normal-state-map "]," 'evil-forward-arg)
    (define-key evil-normal-state-map "[," 'evil-backward-arg)
    (define-key evil-motion-state-map "]," 'evil-forward-arg)
    (define-key evil-motion-state-map "[," 'evil-backward-arg)))

(with-load 'evil-exchange-autoloads
  (set 'evil-exchange-key "sx")
  (set 'evil-exchange-cancel-key "sX")
  (evil-exchange-install)

  (with-load 'evil-args
    (with-load 'evil-exchange-args
      (define-key evil-normal-state-map "sw" 'evil-exchange-forward-arg)
      (define-key evil-normal-state-map "sW" 'evil-exchange-backward-arg))))

;; Evil-Leader
(with-load 'evil-leader-autoloads
  (global-evil-leader-mode t)
  (evil-leader/set-leader "<SPC>")

  (evil-leader/set-key "bb" 'bury-buffer)
  (evil-leader/set-key "bk" 'kill-this-buffer)
  (evil-leader/set-key "bo" 'evil-buffer))

;; Evil-Surround
(with-load 'evil-surround-autoloads
  (global-evil-surround-mode t)

  (with-load 'evil
    (define-key evil-normal-state-map "js" 'evil-surround-region)
    (define-key evil-normal-state-map "jS" 'evil-surround-region)
    (define-key evil-visual-state-map "js" 'evil-surround-region)
    (define-key evil-visual-state-map "jS" 'evil-Surround-region)))

;;;; Extensions

;; Comments
(with-load! 'comment-dwim-toggle
  (with-load 'evil-leader
    (evil-leader/set-key "c" 'comment-dwim-toggle)))

;; Company
(with-load 'company-autoloads
  (global-company-mode t)
  (with-load 'diminish
    (diminish 'company-mode)))

(with-load 'company
  (set 'company-dabbrev-downcase nil)
  (set 'company-dabbrev-ignore-case nil)
  (set 'company-dabbrev-code-ignore-case nil)

  (with-load 'evil
    (define-key company-active-map "\C-e" 'company-select-next)
    (define-key company-active-map "\C-i" 'company-select-previous)))

;; Compilation
(with-load 'compile
  (set 'compilation-scroll-output t)

  (with-load 'evil-leader
    (evil-leader/set-key "rr" 'recompile)
    (evil-leader/set-key "rk" 'kill-compilation))

  (with-load 'ansi-color
    (defun colorize-compilation-buffer ()
      (let ((inhibit-read-only t))
        (ansi-color-apply-on-region (point-min) (point-max))))
    (add-hook 'compilation-filter-hook 'colorize-compilation-buffer)))

(with-load 'compilation-manager
  (with-load 'evil-leader
    (evil-leader/set-key "rp" 'compilation-manager-run-profile)
    (evil-leader/set-key "rn" 'compilation-manager-name-last-profile)))

;; Diminish
(with-load 'diminish-autoloads
  (diminish 'visual-line-mode)
  (diminish 'undo-tree-mode))

;; Dired
(with-load 'dired
  (set 'dired-dwim-target t)
  (set 'dired-listing-switches "-alhD --group-directories-first")

  (add-to-list 'evil-emacs-state-modes 'dired-mode)

  (define-key dired-mode-map "e" 'dired-next-line)
  (define-key dired-mode-map "i" 'dired-previous-line))

;; EDiff
(with-load 'ediff
  (set 'ediff-window-setup-function 'ediff-setup-windows-plain)
  (set 'ediff-split-window-function 'split-window-horizontally))

;; Eldoc
(with-load 'eldoc
  (with-load 'diminish
    (diminish 'eldoc-mode)))

;; EShell
(with-load 'eshell
  (set 'eshell-scroll-show-maximum-output nil)

  (with-hook 'eshell-mode-hook
    (evil-define-key 'insert eshell-mode-map (kbd "<return>") 'eshell-queue-input)))

;; ETags
(with-load 'etags
  (with-load 'evil-leader
    (evil-leader/set-key "tb" 'pop-tag-mark)
    (evil-leader/set-key "tf" 'find-tag)))

;; Expand-Region
(with-load 'expand-region-autoloads
  (with-load 'evil
    (define-key evil-visual-state-map "." 'er/expand-region)))

;; Ffap
(with-load! 'ffap)

;; Flycheck
(with-load 'flycheck-autoloads
  (global-flycheck-mode t)

  (add-to-list 'evil-emacs-state-modes 'flycheck-error-list-mode)

  (with-load 'evil-leader
    (evil-leader/set-key "fe" 'flycheck-next-error)
    (evil-leader/set-key "fi" 'flycheck-previous-error)
    (evil-leader/set-key "fl" 'flycheck-list-errors)
    (evil-leader/set-key "fc" 'flycheck-buffer)))

;; Help
(with-load! 'help-fns+)

;; Ido*
(with-load! 'ido
  (ido-mode t)
  (ido-everywhere t)

  (set 'ido-auto-merge-work-directories-length -1)
  (set 'ido-cannot-complete-command 'ido-next-match)
  (set 'ido-max-prospects 6)

  (with-load 'evil-leader
    (evil-leader/set-key "pb" 'ido-switch-buffer)
    (evil-leader/set-key "pf" 'ido-find-file)
    (evil-leader/set-key "pk" 'ido-kill-buffer))

  (with-load 'ido-ubiquitous-autoloads
    (ido-ubiquitous-mode t))

  (with-load 'ido-vertical-mode-autoloads
    (ido-vertical-mode t))

  (with-hook 'ido-setup-hook
    (define-key ido-completion-map "\C-e" 'ido-next-match)
    (define-key ido-completion-map "\C-i" 'ido-prev-match)
    (define-key ido-completion-map "\C-o" 'ido-restrict-to-matches)

    (define-key ido-completion-map (kbd "<tab>") 'ido-complete-space)
    (define-key ido-completion-map (kbd "<backtab>") 'ido-prev-match)))

;; IMenu
(with-load 'imenu
  (set 'imenu-space-replacement "-")

  (with-load 'evil-leader
    (evil-leader/set-key "pm" 'imenu)))

;; Magit
(with-load 'magit-autoloads
  (with-load 'evil-leader
    (evil-leader/set-key "gs" 'magit-status)
    (evil-leader/set-key "gb" 'magit-blame-mode)))

(with-load 'magit
  (with-load 'evil
    (evil-set-initial-state 'magit-popup-mode 'emacs)
    (evil-set-initial-state 'magit-popup-sequence-mode 'emacs)
    (evil-set-initial-state 'magit-process-mode 'emacs)
    (evil-set-initial-state 'magit-revision-mode 'emacs)

    (evil-define-key 'emacs magit-status-mode-map "n" 'evil-backward-char)
    (evil-define-key 'emacs magit-status-mode-map "e" 'evil-next-line)
    (evil-define-key 'emacs magit-status-mode-map "i" 'evil-previous-line)
    (evil-define-key 'emacs magit-status-mode-map "o" 'evil-forward-char)

    (evil-define-key 'emacs magit-status-mode-map "\S-n" 'magit-section-backward-sibling)
    (evil-define-key 'emacs magit-status-mode-map "\S-e" 'magit-section-forward)
    (evil-define-key 'emacs magit-status-mode-map "\S-i" 'magit-section-backward)
    (evil-define-key 'emacs magit-status-mode-map "\S-o" 'magit-section-forward-sibling)

    (evil-define-key 'emacs magit-status-mode-map "\M-i" 'magit-section-up)

    (evil-define-key 'emacs magit-diff-mode-map "n" 'evil-backward-char)
    (evil-define-key 'emacs magit-diff-mode-map "e" 'evil-next-line)
    (evil-define-key 'emacs magit-diff-mode-map "i" 'evil-previous-line)
    (evil-define-key 'emacs magit-diff-mode-map "o" 'evil-forward-char)

    (evil-define-key 'emacs magit-diff-mode-map "\S-e" 'magit-section-forward)
    (evil-define-key 'emacs magit-diff-mode-map "\S-i" 'magit-section-backward)

    (evil-define-key 'emacs magit-log-mode-map "e" 'magit-section-forward)
    (evil-define-key 'emacs magit-log-mode-map "i" 'magit-section-backward)))

;; Multiple-Cursors
(with-load 'multiple-cursors-autoloads
  (with-load 'evil-leader
    (evil-leader/set-key "mt" 'mc/mark-all-like-this-dwim)))

;; Smart-Parens
(with-load 'smartparens-autoloads
  (smartparens-global-strict-mode)
  (set 'post-self-insert-hook nil)
  (smartparens-global-mode))

(with-load 'smartparens
  (with-load 'diminish
    (diminish 'smartparens-mode))

  (sp-pair "'" "'" :unless '(sp-point-after-word-p))

  (sp-local-pair 'emacs-lisp-mode "`" "`" :actions nil)
  (sp-local-pair 'lisp-interaction-mode "`" "`" :actions nil)

  (sp-local-pair 'emacs-lisp-mode "`" "'" :when '(sp-in-string-p))
  (sp-local-pair 'lisp-interaction-mode "`" "'" :when '(sp-in-string-p))

  (sp-local-pair 'emacs-lisp-mode "'" nil :actions nil)
  (sp-local-pair 'lisp-interaction-mode "'" nil :actions nil)

  (with-load 'evil
    (set 'sp-fast-map (make-sparse-keymap))
    (define-key evil-normal-state-map "sk" sp-fast-map)

    (define-key sp-fast-map "n" 'sp-previous-sexp)
    (define-key sp-fast-map "e" 'sp-down-sexp)
    (define-key sp-fast-map "i" 'sp-up-sexp)
    (define-key sp-fast-map "o" 'sp-next-sexp)

    (define-key sp-fast-map "\M-n" 'sp-backward-slurp-sexp)
    (define-key sp-fast-map "\M-\S-n" 'sp-backward-barf-sexp)
    (define-key sp-fast-map "\M-o" 'sp-forward-slurp-sexp)
    (define-key sp-fast-map "\M-\S-o" 'sp-forward-barf-sexp)

    (define-key sp-fast-map "j" 'sp-join-sexp)
    (define-key sp-fast-map "k" 'sp-kill-sexp)
    (define-key sp-fast-map "l" 'sp-emit-sexp)
    (define-key sp-fast-map "r" 'sp-raise-sexp)
    (define-key sp-fast-map "s" 'sp-split-sexp)))

;; SMex
(with-load 'smex-autoloads
  (smex-initialize)
  (global-set-key "\M-x" 'smex)
  (global-set-key "\M-X" 'smex-major-mode-commands)
  (global-set-key "\C-c\C-c\M-x" 'execute-extended-command))

;; Undo
(with-load 'undo-tree
  (with-load 'evil
    (define-key evil-normal-state-map "u" 'undo-tree-undo)
    (define-key evil-normal-state-map "U" 'undo-tree-redo)

    (evil-set-initial-state 'undo-tree-visualizer-mode 'emacs)

    (define-key undo-tree-visualizer-mode-map "n" 'undo-tree-visualize-switch-branch-left)
    (define-key undo-tree-visualizer-mode-map "e" 'undo-tree-visualize-redo)
    (define-key undo-tree-visualizer-mode-map "i" 'undo-tree-visualize-undo)
    (define-key undo-tree-visualizer-mode-map "o" 'undo-tree-visualize-switch-branch-right))

  (with-load 'evil-leader
    (evil-leader/set-key "u" 'undo-tree-visualize)))

;;; Volatile Highlights
(with-load 'volatile-highlights-autoloads
  (volatile-highlights-mode t)
  (with-load 'diminish
    (diminish 'volatile-highlights-mode)))

;;; YASnippet
(with-load 'yasnippet-autoloads
  (set 'yas-snippet-dirs (list (concat user-emacs-directory "snippets")))
  (yas-global-mode))

(with-load 'yasnippet
  (with-load 'diminish
    (diminish 'yas-minor-mode))
  (set-default 'yas-prompt-functions '(yas-ido-prompt))

  (with-load 'evil
    (define-key evil-insert-state-map "\C-o" nil))

  ; This is one of the most aggressive keybinds in existence.
  (define-key yas-minor-mode-map (kbd "TAB") nil)
  (define-key yas-minor-mode-map [(tab)] nil)

  (define-key yas-minor-mode-map "\C-o" 'yas-expand))

;;;; Major Modes

;; General Programming Mode configuration.
(with-load 'fic-mode-autoloads
  (with-hook 'prog-mode-hook
    (turn-on-fic-mode)))

(with-load 'fic-mode
  (with-load 'diminish
    (diminish 'fic-mode)))

(with-load 'bibtex
  (setc 'bibtex-dialect 'BibTeX))

;; TeX/LaTeX/AucTeX/RefTeX
(with-load 'latex
  (set 'font-latex-fontify-sectioning 'color)

  (set 'LaTeX-indent-level 2)
  (set 'LaTeX-item-indent 0)

  (TeX-global-PDF-mode t)
  (TeX-source-correlate-mode t)

  (set-default 'LaTeX-verbatim-environments-local '("Verbatim"))

  (set 'TeX-source-correlate-method 'synctex)
  (set 'TeX-newline-function 'reindent-then-newline-and-indent)

  (add-to-list 'LaTeX-indent-environment-list '("minted" current-indentation))

  (add-to-list 'TeX-expand-list `("%i" (lambda () ,instance-name)))

  (add-to-list 'TeX-view-program-list '("QPDFView"
    ("qpdfview --unique --instance %i %o" (mode-io-correlate "#src:%b:%n:1"))))

  (setcdr (assoc 'output-pdf TeX-view-program-selection) '("QPDFView"))

  (with-load! 'TeX-indent-item-continuation
   (upsert-alist "enumerate" '(LaTeX-indent-item) LaTeX-indent-environment-list)
   (upsert-alist "description" '(LaTeX-indent-item) LaTeX-indent-environment-list)
   (upsert-alist "itemize" '(LaTeX-indent-item) LaTeX-indent-environment-list))

  (with-load! 'auctex-latexmk
    (auctex-latexmk-setup))

  (with-load 'evil-leader
    (evil-leader/set-key-for-mode 'latex-mode "lv" 'TeX-view)
    (evil-leader/set-key-for-mode 'latex-mode "li" 'reftex-toc)
    (with-load 'TeX-texify
      (evil-leader/set-key-for-mode 'latex-mode "ll" 'TeX-texify)))

  (with-load 'flycheck
    (set 'flycheck-chktexrc (expand-file-name "~/.chktexrc")))

  (with-load 'reftex
    (set 'reftex-plug-into-AUCTeX t))

  (with-load 'reftex-toc
    (define-key reftex-toc-map "e" 'reftex-toc-next)
    (define-key reftex-toc-map "i" 'reftex-toc-previous))

  (with-load! 'TeX-texify
    (set 'TeX-texify-Show nil))

  (with-hook 'LaTeX-mode-hook
    (auto-fill-mode)
    (turn-on-reftex)))

;; C/C++ Modes
(with-load 'cc-mode
  (set 'c-basic-offset 2)
  (c-set-offset 'access-label '/)
  (with-load! 'prepaint
    (prepaint-global-mode t)
    (with-hook 'c-mode-common-hook
      (face-remap-add-relative 'prepaint-face 'font-lock-variable-name-face))))

(with-load 'c++-mode
  (with-load 'flycheck
    (set 'flycheck-clang-language-standard "c++1y")))

;; Emacs-Lisp
(with-load 'emacs
  (with-load 'paredit-autoloads
    (with-hook 'emacs-lisp-mode-hook
      (paredit-mode t)))

  (with-hook 'emacs-lisp-mode-hook
    (turn-on-eldoc-mode)

    (with-load 'flycheck
      (add-to-list 'flycheck-disabled-checkers 'emacs-lisp-checkdoc))

    (font-lock-add-keywords nil '(("(\\(\\<with-load!?\\>\\)" 1 'font-lock-keyword-face)))
    (font-lock-add-keywords nil '(("(\\(\\<with-hook\\>\\)" 1 'font-lock-keyword-face)))


    (set 'imenu-prev-index-position-function nil)
    (add-to-list 'imenu-generic-expression '("Sections" "^;;;; \\(.+\\)$" 1) t)))

;; Haskell
(with-load 'haskell-mode
  (with-hook 'haskell-mode-hook
    (turn-on-haskell-decl-scan)
    (turn-on-haskell-doc)
    (turn-on-haskell-indent)

    (with-load 'diminish
      (diminish 'haskell-doc-mode)
      (diminish 'haskell-indent-mode))

    (face-remap-add-relative 'font-lock-doc-face 'font-lock-comment-face))

  (with-load 'flycheck
    (with-hook 'flycheck-mode-hook
      #'flycheck-haskell-setup)))

;; Ledger
(with-load 'ledger-mode-autoloads
  (set 'ledger-clear-whole-transactions t)
  (set 'ledger-post-amount-alignment-column 80)
  (set 'ledger-reconcile-default-commodity "USD")
  (set 'ledger-reports
       '(("account" "ledger -f %(ledger-file) register %(account)")
         ("balance" "ledger -f %(ledger-file) balance")
         ("payee" "ledger -f %(ledger-file) register @%(payee)")
         ("register" "ledger -f %(ledger-file) register")))

  ; Not really specific to ledger, but close enough.
  (set 'pcomplete-termination-string "")

  (with-load 'evil
    (evil-set-initial-state 'ledger-report-mode 'emacs))

  (with-load 'evil-leader
    (evil-leader/set-key-for-mode 'ledger-mode "lq" 'ledger-post-align-xact)
    (evil-leader/set-key-for-mode 'ledger-mode "lr" 'ledger-report))

  (with-load 'flycheck
    (require 'flycheck-ledger)
    (set 'flycheck-ledger-pedantic t)))

;; Org-Mode
(with-load 'org-autoloads
  (with-load 'evil-leader
    (evil-leader/set-key "oa" 'org-agenda)
    (evil-leader/set-key "oc" 'org-capture)))

(with-load 'org
  (set 'org-directory "~/org/")
  (set 'org-agenda-files '("~/org/staging.org" "~/org/agenda"))
  (set 'org-drawers '("LOG" "CLOCK" "PROPERTIES" "RESULTS"))

  (set 'org-adapt-indentation nil)

  (set 'org-attach-auto-tag "@")
  (set 'org-attach-file-list-property "ATTACHMENTS")

  (set 'org-edit-src-content-indentation 0)

  (set 'org-file-apps `((auto-mode . emacs)
                        ("\\.pdf::\\([0-9]+\\)" . ,(format "qpdfview --unique --instance %s %%s#%%1" instance-name))
                        ("\\.ps" . ,(format "qpdfview --unique --instance %s %%s" instance-name))
                        ("\\.pdf" . ,(format "qpdfview --unique --instance %s %%s" instance-name))))

  (set 'org-log-into-drawer "LOG")

  (set 'org-refile-use-outline-path 'file)
  (set 'org-refile-targets '((org-agenda-files :maxlevel . 9)))

  (set 'org-capture-templates
       `(("a" "Appointment" entry (file+headline ,(concat org-directory "agenda/schedule.org") "Impromptu")
          "* %^{Subject}\n%^T\n%?" :kill-buffer t :prepend t)
         ("i" "Idea" entry (file+headline ,(concat org-directory "staging.org") "Ideas")
          "* %^{Subject}\n%?" :kill-buffer t :prepend t)
         ("l" "Link" entry (file+headline ,(concat org-directory "staging.org") "Links")
          "* %^{Description}: [[%x]]\n" :kill-buffer t :immediate-finish t)
         ("n" "Note" entry (file+headline ,(concat org-directory "staging.org") "Notes")
          "* %^{Subject}\n%?" :kill-buffer t :prepend t)
         ("t" "Task" entry (file+headline (concat org-directory "staging.org") "Tasks")
          "* TODO %?" :kill-buffer t :prepend t)))

  ; Predominantly, I want to start capture typing text, not commands.
  (with-hook 'org-capture-mode-hook
      (evil-insert-state))

  (set 'org-edit-src-indentation 0)
  (set 'org-ellipsis "…")

  (set 'org-src-fontify-natively t)

  (set 'org-agenda-tags-column -100)
  (set 'org-tags-column -100)

  (defun org-tags-attachment-last (x y)
    (if (string= org-attach-auto-tag x) nil
      (if (string= org-attach-auto-tag y) t
        (string< x y))))

  (set 'org-tags-sort-function 'org-tags-attachment-last)

  ;; Org-Babel
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((calc . t)
     (sh . t)))

  (with-load 'ob-sh
    (if (executable-find "zsh")
        (set 'org-babel-sh-command "zsh")))

  (add-to-list 'evil-emacs-state-modes 'org-agenda-mode)

  (with-load 'evil
    (evil-define-key 'normal org-mode-map "\M-n" 'org-metaleft)
    (evil-define-key 'normal org-mode-map "\M-e" 'org-metadown)
    (evil-define-key 'normal org-mode-map "\M-i" 'org-metaup)
    (evil-define-key 'normal org-mode-map "\M-o" 'org-metaright)

    (evil-define-key 'normal org-mode-map "\S-n" 'org-shiftleft)
    (evil-define-key 'normal org-mode-map "\S-e" 'org-shiftdown)
    (evil-define-key 'normal org-mode-map "\S-i" 'org-shiftup)
    (evil-define-key 'normal org-mode-map "\S-o" 'org-shiftright)

    (evil-define-key 'insert org-mode-map "\M-n" 'org-metaleft)
    (evil-define-key 'insert org-mode-map "\M-e" 'org-metadown)
    (evil-define-key 'insert org-mode-map "\M-i" 'org-metaup)
    (evil-define-key 'insert org-mode-map "\M-o" 'org-metaright)

    (evil-define-key 'normal org-mode-map "\M-\S-n" 'org-shiftmetaleft)
    (evil-define-key 'normal org-mode-map "\M-\S-e" 'org-shiftmetadown)
    (evil-define-key 'normal org-mode-map "\M-\S-i" 'org-shiftmetaup)
    (evil-define-key 'normal org-mode-map "\M-\S-o" 'org-shiftmetaright)

    (evil-define-key 'emacs org-agenda-mode-map "e" 'org-agenda-next-item)
    (evil-define-key 'emacs org-agenda-mode-map "i" 'org-agenda-previous-item)

    (with-load! 'org-open-heading
      (evil-define-key 'normal org-mode-map "\M-y" 'org-open-heading-below-and-insert)
      (evil-define-key 'normal org-mode-map "\M-Y" 'org-open-heading-above-and-insert)))

  (with-hook 'org-mode-hook
    (auto-fill-mode t))

  (with-hook 'org-agenda-mode-hook
    (hl-line-mode)))

(provide 'init)
;;; init.el ends here
