# Configuration file for latexmk, a LaTeX compilation tool.

$latex = 'latex --shell-escape';
$pdflatex = 'xelatex -shell-escape -interaction=nonstopmode -file-line-error -synctex=1';

$pdf_previewer = 'qpdfview';
$pdf_mode = 1;
$bibtex_use = 2;

$clean_ext = 'sta'
